name: BERT_NO_POOL

st1_encoder:
  _target_: source.encoder.BertEncoder.BertEncoder
  architecture: bert-base-uncased
  output_attentions: False
  pooling:
    _target_: source.pooling.NoPooling.NoPooling

st2_encoder:
  _target_: source.encoder.BertEncoder.BertEncoder
  architecture: bert-base-uncased
  output_attentions: False
  pooling:
    _target_: source.pooling.NoPooling.NoPooling

hidden_size: 768

st1_tokenizer:
  architecture: ${model.st1_encoder.architecture}

st2_tokenizer:
  architecture: ${model.st2_encoder.architecture}

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3
weight_decay: 1e-2

loss:
  _target_: source.loss.CosineEmbeddingLoss.CosineEmbeddingLoss
  name: CossineEmbeddingLoss

stat:
  dir: resource/stat/
  name: ${model.name}_${data.name}.stat