name: GRU

desc_encoder:
  _target_: source.encoder.GRUEncoder.GRUEncoder
  vocabulary_size: ${model.vocabulary_size}
  representation_size: ${model.hidden_size}
  hidden_size: ${model.hidden_size}
  pooling:
    _target_: source.pooling.AveragePooling.AveragePooling

code_encoder:
  _target_: source.encoder.GRUEncoder.GRUEncoder
  vocabulary_size: ${model.vocabulary_size}
  representation_size: ${model.hidden_size}
  hidden_size: ${model.hidden_size}
  pooling:
    _target_: source.pooling.AveragePooling.AveragePooling

hidden_size: 768
vocabulary_size: 50000

desc_tokenizer:
  architecture: microsoft/codebert-base

code_tokenizer:
  architecture: microsoft/codebert-base

lr: 1e-5
base_lr: 1e-7
max_lr: 1e-3
weight_decay: 1e-2

loss:
  _target_: source.loss.NPairsLoss.NPairsLoss
  name: N-Pair-Loss

stat:
  dir: resource/stat/
  name: ${model.name}_${data.name}.stat